development:
  daily_cleanup:
    class: CleanupJob
    schedule: at 3am every day
  refresh_slack_channels_cache:
    class: RefreshSlackChannelsCacheJob
    schedule: every day at 4am

production:
  daily_cleanup:
    class: CleanupJob
    schedule: at 3am every day
  refresh_slack_channels_cache:
    class: RefreshSlackChannelsCacheJob
    schedule: every day at 4am

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
